### ISSUE TITLE
Training steps

### ISSUE THREAD

**Issue by xjoshramos** [bernard24/RIS#3]
When training for plants I am getting an error on the following line.

./plants_utils.lua:93: in function 'create_instance'

I have downloaded the data and dropped in the proper folders. Created the following files.

list_filename = input_path .. 'data_list.txt'
labels_filename = gt_path .. 'label_list.txt'

What are the steps to training?

**Comment by bernard24** [comment]
The ground truth images need to be formatted. For the time being, I have added a matlab script that can do it: https://github.com/bernard24/RIS/blob/master/plants_learning/format_labels.m
Let me know if you have any problem after this step is done.

**Comment by xjoshramos** [comment]
Is this step also required for peoples training?

**Comment by xjoshramos** [comment]
reformatted images and now i am getting this error.

<image.load> unable to determine image type for file: ../Data/LSCData/A1/

**Comment by xjoshramos** [comment]
./Data/LSCData/A1/plant061_rgb.png. 562/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant062_rgb.png. 563/100000 ..................................]  ETA: 3h56m | Step: 142ms     
test: ../Data/LSCData/A1/plant063_rgb.png. 564/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant064_rgb.png. 565/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant065_rgb.png. 566/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant067_rgb.png. 567/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant068_rgb.png. 568/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant069_rgb.png. 569/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant070_rgb.png. 570/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant071_rgb.png. 571/100000 ..................................]  ETA: 3h55m | Step: 141ms     
test: ../Data/LSCData/A1/plant072_rgb.png. 572/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant073_rgb.png. 573/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant076_rgb.png. 574/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant077_rgb.png. 575/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant078_rgb.png. 576/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant079_rgb.png. 577/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant080_rgb.png. 578/100000 ..................................]  ETA: 3h55m | Step: 142ms     
test: ../Data/LSCData/A1/plant082_rgb.png. 579/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant083_rgb.png. 580/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant084_rgb.png. 581/100000 ..................................]  ETA: 3h54m | Step: 141ms     
test: ../Data/LSCData/A1/plant085_rgb.png. 582/100000 ..................................]  ETA: 3h54m | Step: 141ms

**Comment by xjoshramos** [comment]
never mind i have it training.... great work... 

I will be training with my own data for a specific case. Would like me to submit you the model after it is trained?

**Comment by xjoshramos** [comment]
For people without matlab. Copy format_labels.m into the directory to format the annotated images and use octave. Images should look like:

![plant042_label](https://cloud.githubusercontent.com/assets/4721207/20023860/fd5460be-a29f-11e6-962a-c320cdf951a0.png)

**Comment by bernard24** [comment]
Thanks a lot @xjoshramos.
Btw, feel free to submit any new model you train. Any contribution is welcome.
