### ISSUE TITLE
inference for plants

### ISSUE THREAD

**Issue by xjoshramos** [bernard24/RIS#6]
Inference for plants trained.

**Comment by xjoshramos** [comment]
error is on this line....

local lst = protos.rnn:forward{x, unpack(current_state)}

**Comment by xjoshramos** [comment]
![test](https://cloud.githubusercontent.com/assets/4721207/20077157/125ee612-a4f0-11e6-8b04-007d1cb5e7d2.jpeg)

**Comment by xjoshramos** [comment]
I am getting this output for the first plant test image. Is this correct?

**Comment by xjoshramos** [comment]
![plant001_rgb](https://cloud.githubusercontent.com/assets/4721207/20077475/6ff84358-a4f1-11e6-850f-0cd89cd12b51.png)

**Comment by xjoshramos** [comment]
![in](https://cloud.githubusercontent.com/assets/4721207/20077504/89e26258-a4f1-11e6-9b9a-572e891521d7.jpeg)

**Comment by bernard24** [comment]
This does not look correct.
Have you been training with the default launcher? For how long? What is the training error you are getting at the end (in the log)?

**Comment by xjoshramos** [comment]
using the default launcher...

[======================================== 100000/100000 ==============================>]  Tot: 3h32m | Step: 127ms  
test: ../Data/LSCData/A1/plant042_rgb.png   

==> time to learn 1 sample = 127.37543668032ms  
-0.60202038425659

**Comment by Liu0329** [comment]
@xjoshramos @bernard24  Hi guys, I have downloaded the Plant_Phenotyping_Datasets dataset, but I cannot find the LSCData folder. Did I download the correct dataset ? Could you provide a link ?

**Comment by xjoshramos** [comment]
http://www.plant-phenotyping.org/CVPPP2014-dataset

**Comment by bernard24** [comment]
Thanks @xjoshramos.
The training loss error you are reporting is not as low as it should be (for seq_length=2), so I would train the model for a bit longer. You can have a look at usual training loss values, as well as typical results in this issue: [https://github.com/bernard24/RIS/issues/2](https://github.com/bernard24/RIS/issues/2).
