### ISSUE TITLE
Sometimes there are more than 1 instance in a specific step of lstm, what might be a solution to this problem?

### ISSUE THREAD

**Issue by brisker** [bernard24/RIS#7]
Sometimes there are more than 1 instance in a specific step of lstm, what might be a solution to this problem? What might be the reason and what might be a solution(modify the model) ?

**Comment by bernard24** [comment]
The model tries to learn from the training set, but its performance is not perfect, and sometimes it makes errors as the ones you mention. There are two potential, and complementary, approaches to amend this:
1.- Adding more training data: for example, in the plants dataset, there are only 128 training images (which are augmented by randomly rotating and flipping them). A bigger training dataset probably leads to a more robust learned model.
2.- As you mention, another approach is to modify the model. This is a research problem in itself, and there may be many different ways this can be done. Luckily, instance segmentation is receiving quite a lot of attention nowadays, with new papers appearing presenting original ideas. You can have a look at them, and maybe combine some of their ideas with this framework, or maybe you come up with a new more robust framework.
